apiVersion: apps/v1
kind: Deployment
metadata:
   name: mydep
spec:
  template:
    metadata:
      name: mypod
      labels:
        app: web
    spec:
      containers:
        - name: nginx
          image: gcr.io/PROJECT_ID/IMAGE:TAG
          imagePullPolicy: Always
  replicas: 1
  selector:
    matchLabels:
      app: web
